Repository CS2113-AY1819S1-F09-4/main, pull requests merged in 2018-11, with the labels that each got.

#125 Updated user guide and dev guide. Added reverse sort for companies(missed that out)
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/mingxunseah.adoc
  src/main/java/seedu/recruit/logic/commands/SelectCandidateCommand.java
  src/main/java/seedu/recruit/model/CompanyBook.java
  src/main/java/seedu/recruit/model/company/UniqueCompanyList.java
Labels: priority.medium, type.bug

#126 Updated dev guide and ppp
  docs/DeveloperGuide.adoc
  docs/team/mingxunseah.adoc
Labels: priority.medium

#127 Added sort command for job offers. Updated UGDG as well.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/mingxunseah.adoc
  src/main/java/seedu/recruit/logic/commands/SortJobOfferCommand.java
  src/main/java/seedu/recruit/logic/parser/RecruitBookParser.java
  src/main/java/seedu/recruit/logic/parser/SortCandidateCommandParser.java
  src/main/java/seedu/recruit/logic/parser/SortCompanyCommandParser.java
  src/main/java/seedu/recruit/logic/parser/SortJobOfferCommandParser.java
  src/main/java/seedu/recruit/model/CompanyBook.java
  src/main/java/seedu/recruit/model/Model.java
  src/main/java/seedu/recruit/model/ModelManager.java
  src/main/java/seedu/recruit/model/joboffer/UniqueJobList.java
  src/test/java/seedu/recruit/logic/commands/CommandTestUtil.java
Labels: priority.high, type.enhancement, type.story

#128 Updated Ui font, Logo, and Ui.png file and Readme doc
  README.adoc
  docs/images/Ui.png
  src/main/java/seedu/recruit/logic/commands/CancelCommand.java
  src/main/java/seedu/recruit/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/logo.png
  src/main/resources/view/CandidateCard.fxml
  src/main/resources/view/CandidateDetailsPanel.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/CompanyCard.fxml
  src/main/resources/view/CompanyJobDetailsPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EmailPreview.fxml
  src/main/resources/view/JobCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NixieOne-Regular.otf
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/ShortlistPanel.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/recruit/commons/util/AppUtilTest.java
Labels: type.enhancement

#133 Added potential bug fixes before pe 1
  docs/team/kianmengtan.adoc
  src/main/java/seedu/recruit/logic/commands/BlacklistCommand.java
  src/main/java/seedu/recruit/logic/commands/EditCandidateCommand.java
  src/main/java/seedu/recruit/model/CompanyBook.java
  src/main/java/seedu/recruit/model/ModelManager.java
  src/main/java/seedu/recruit/ui/CandidateCard.java
Labels: severity.High, type.bug

#140 Added shortlist and unshortlist tags
  src/main/java/seedu/recruit/logic/commands/BlacklistCommand.java
  src/main/java/seedu/recruit/logic/commands/DeleteShortlistedCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/ShortlistCandidateCommand.java
Labels: type.bug

#175 Added Add-Company/Candidate 'interface'
  docs/UserGuide.adoc
  src/main/java/seedu/recruit/commons/core/Messages.java
  src/main/java/seedu/recruit/logic/commands/AddCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/AddJobDetailsCommand.java
  src/main/java/seedu/recruit/logic/commands/ClearCandidateBookCommand.java
  src/main/java/seedu/recruit/logic/commands/ClearCompanyBookCommand.java
  src/main/java/seedu/recruit/logic/commands/RedoCandidateBookCommand.java
  src/main/java/seedu/recruit/logic/commands/RedoCompanyBookCommand.java
  src/main/java/seedu/recruit/logic/commands/StartAddCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/StartAddCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/StartAddJobCommand.java
  src/main/java/seedu/recruit/logic/commands/UndoCandidateBookCommand.java
  src/main/java/seedu/recruit/logic/commands/UndoCompanyBookCommand.java
  src/main/java/seedu/recruit/logic/parser/AddCandidateCommandParser.java
  src/main/java/seedu/recruit/logic/parser/AddCompanyCommandParser.java
  src/main/java/seedu/recruit/logic/parser/AddJobDetailsCommandParser.java
  src/main/java/seedu/recruit/logic/parser/RecruitBookParser.java
  src/main/java/seedu/recruit/model/joboffer/JobOffer.java
  src/test/java/seedu/recruit/logic/parser/AddCandidateCommandParserTest.java
  src/test/java/seedu/recruit/logic/parser/AddCompanyCommandParserTest.java
  src/test/java/seedu/recruit/logic/parser/RecruitBookParserTest.java
  src/test/java/seedu/recruit/testutil/ModelUtil.java
  src/test/java/systemtests/AddCandidateCommandSystemTest.java
  src/test/java/systemtests/EditCandidateCommandSystemTest.java
Labels: priority.medium, type.enhancement

#188 Fixed company name error which does not cascade
  src/main/java/seedu/recruit/logic/commands/EditCompanyCommand.java
  src/main/java/seedu/recruit/model/CompanyBook.java
  src/main/java/seedu/recruit/model/Model.java
  src/main/java/seedu/recruit/model/ModelManager.java
  src/test/java/seedu/recruit/logic/commands/CommandTestUtil.java
Labels: type.bug

#189 Fixed editj bug
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/recruit/logic/commands/EditJobDetailsCommand.java
  src/main/java/seedu/recruit/logic/parser/EditJobDetailsCommandParser.java
Labels: type.bug

#197 Fixed masterList not hiding with password
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoNewCommand4StateListDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
  docs/team/sxqnicholas.adoc
  src/main/java/seedu/recruit/commons/core/Messages.java
  src/main/java/seedu/recruit/logic/commands/AddCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/AddJobDetailsCommand.java
  src/main/java/seedu/recruit/logic/commands/AuthenticateUserCommand.java
  src/main/java/seedu/recruit/logic/commands/CancelCommand.java
  src/main/java/seedu/recruit/logic/commands/SetPasswordCommand.java
  src/main/java/seedu/recruit/logic/parser/EmailParser.java
  src/main/java/seedu/recruit/model/ModelManager.java
  src/main/java/seedu/recruit/ui/MainWindow.java
  src/test/java/systemtests/CandidateBookSystemTest.java
Labels: priority.high, type.task

#204 Reworked setLogicState mechanism, added password hashing
  src/main/java/seedu/recruit/commons/events/logic/ChangeLogicStateEvent.java
  src/main/java/seedu/recruit/logic/LogicManager.java
  src/main/java/seedu/recruit/logic/LogicState.java
  src/main/java/seedu/recruit/logic/commands/AuthenticateUserCommand.java
  src/main/java/seedu/recruit/logic/commands/CancelCommand.java
  src/main/java/seedu/recruit/logic/commands/DeleteShortlistedCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/DeleteShortlistedCandidateInitializationCommand.java
  src/main/java/seedu/recruit/logic/commands/FilterCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/FilterCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/FindCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/FindCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/SelectCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/SelectCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/SelectJobCommand.java
  src/main/java/seedu/recruit/logic/commands/SetPasswordCommand.java
  src/main/java/seedu/recruit/logic/commands/ShortlistCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/ShortlistCandidateInitializationCommand.java
  src/main/java/seedu/recruit/logic/commands/SortCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/SortCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/SortJobOfferCommand.java
  src/main/java/seedu/recruit/logic/commands/StartAddCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/StartAddCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/StartAddJobCommand.java
  src/main/java/seedu/recruit/logic/commands/StartSetPasswordCommand.java
  src/main/java/seedu/recruit/logic/commands/emailcommand/EmailContentsBackCommand.java
  src/main/java/seedu/recruit/logic/commands/emailcommand/EmailContentsNextCommand.java
  src/main/java/seedu/recruit/logic/commands/emailcommand/EmailInitialiseCommand.java
  src/main/java/seedu/recruit/logic/commands/emailcommand/EmailRecipientsNextCommand.java
  src/main/java/seedu/recruit/logic/commands/emailcommand/EmailSendBackCommand.java
  src/main/java/seedu/recruit/logic/commands/emailcommand/EmailSendSendCommand.java
  src/main/java/seedu/recruit/logic/parser/RecruitBookParser.java
  src/main/java/seedu/recruit/model/RecruitBook.java
  src/main/java/seedu/recruit/ui/MainWindow.java
  src/test/java/systemtests/CandidateBookSystemTest.java
Labels: priority.medium, type.task

#205 User can now undo/redo changes in Add Company/Job/Candidate interface
  docs/UserGuide.adoc
  src/main/java/seedu/recruit/logic/commands/AddCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/AddJobDetailsCommand.java
  src/main/java/seedu/recruit/logic/parser/AddCandidateCommandParser.java
  src/main/java/seedu/recruit/logic/parser/AddCompanyCommandParser.java
  src/main/java/seedu/recruit/logic/parser/AddJobDetailsCommandParser.java
Labels: priority.medium, type.enhancement

#211 Populated Sample Data, Added Tests to Model, Fixed Age checking
  src/main/java/seedu/recruit/logic/parser/ParserUtil.java
  src/main/java/seedu/recruit/model/candidate/Age.java
  src/main/java/seedu/recruit/model/joboffer/AgeRange.java
  src/main/java/seedu/recruit/model/joboffer/Job.java
  src/main/java/seedu/recruit/model/joboffer/JobOffer.java
  src/main/java/seedu/recruit/model/util/SampleDataUtil.java
  src/main/java/seedu/recruit/storage/XmlAdaptedJobOffer.java
  src/test/java/seedu/recruit/logic/parser/ParserUtilTest.java
  src/test/java/seedu/recruit/model/candidate/AgeTest.java
  src/test/java/seedu/recruit/model/candidate/CandidateTest.java
  src/test/java/seedu/recruit/model/candidate/EducationTest.java
  src/test/java/seedu/recruit/model/candidate/GenderTest.java
  src/test/java/seedu/recruit/model/commons/AddressTest.java
  src/test/java/seedu/recruit/model/commons/EmailTest.java
  src/test/java/seedu/recruit/model/commons/PhoneTest.java
  src/test/java/seedu/recruit/model/company/CompanyNameTest.java
  src/test/java/seedu/recruit/model/company/CompanyTest.java
  src/test/java/seedu/recruit/model/joboffer/AgeRangeTest.java
  src/test/java/seedu/recruit/model/joboffer/JobTest.java
  src/test/java/seedu/recruit/model/joboffer/SalaryTest.java
Labels: priority.medium

#212 Added tests for sorting, blacklist and edit company
  src/main/java/seedu/recruit/logic/commands/BlacklistCommand.java
  src/main/java/seedu/recruit/logic/commands/EditCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/EditJobDetailsCommand.java
  src/main/java/seedu/recruit/logic/commands/SortCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/SortCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/SortJobOfferCommand.java
  src/main/java/seedu/recruit/model/ModelManager.java
  src/test/data/XmlSerializableCandidateBookTest/typicalPersonsCandidateBook.xml
  src/test/java/seedu/recruit/logic/commands/BlacklistCommandTest.java
  src/test/java/seedu/recruit/logic/commands/EditCompanyCommandTest.java
  src/test/java/seedu/recruit/logic/commands/EditCompanyDescriptorTest.java
  src/test/java/seedu/recruit/logic/commands/SortCandidateCommandTest.java
  src/test/java/seedu/recruit/logic/commands/SortCompanyCommandTest.java
  src/test/java/seedu/recruit/logic/commands/SortJobOfferCommandTest.java
  src/test/java/seedu/recruit/logic/parser/BlacklistCommandParserTest.java
  src/test/java/seedu/recruit/logic/parser/RecruitBookParserTest.java
  src/test/java/seedu/recruit/logic/parser/SortCandidateCommandParserTest.java
  src/test/java/seedu/recruit/logic/parser/SortCompanyCommandParserTest.java
  src/test/java/seedu/recruit/logic/parser/SortJobOfferCommandParserTest.java
  src/test/java/seedu/recruit/testutil/EditJobOfferDescriptorBuilder.java
  src/test/java/seedu/recruit/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/recruit/testutil/ModelUtil.java
  src/test/java/seedu/recruit/testutil/TypicalCompaniesAndJobOffers.java
  src/test/java/seedu/recruit/testutil/TypicalPersons.java
Labels: type.task

#214 Updated UG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/SetPasswordWelcomeMessage.PNG
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoNewCommand4StateListDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
  docs/images/addingRB.gif
  docs/team/sxqnicholas96.adoc
  src/main/java/seedu/recruit/logic/commands/AddJobDetailsCommand.java
  src/main/java/seedu/recruit/logic/commands/CancelCommand.java
  src/main/java/seedu/recruit/logic/commands/SetPasswordCommand.java
  src/main/java/seedu/recruit/model/company/Company.java
  src/main/java/seedu/recruit/model/util/SampleDataUtil.java
  src/main/java/seedu/recruit/ui/MainWindow.java
Labels: priority.high, type.task

#219 Added uml diagrams
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/BlacklistSequenceDiagram.pptx
  docs/diagrams/EditSequenceDiagram.pptx
  docs/diagrams/SortActivityDiagram.pptx
  docs/diagrams/SortSequenceDiagram.pptx
  docs/diagrams/~$ShortlistActivityDiagram.pptx
  docs/diagrams/~$UndoRedoSequenceDiagram.pptx
  docs/images/BlacklistSequenceDiagram.png
  docs/images/BlacklistTag.png
  docs/images/EditSequenceDiagram.png
  docs/images/SortActivityDiagram.png
  docs/images/SortSequenceDiagram.png
Labels: priority.medium, type.task

#221 Updated diagrams in DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/UndoRedoActivityDiagram.pptx
  docs/diagrams/UndoRedoExecuteUndoStateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand1StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand2StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand3StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand4StateListDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/diagrams/UndoRedoStartingStateListDiagram.pptx
  docs/images/LogicComponentClassDiagram.png
  docs/images/SDforDeleteCompany.png
  docs/images/SDforDeleteCompanyEventHandling.png
  docs/images/SDforDeletePerson.png
  docs/images/SDforDeletePersonEventHandling.png
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoNewCommand4StateListDiagram.png
  docs/images/UndoRedoSequenceDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
  docs/team/sxqnicholas96.adoc
Labels: priority.high
