Repository CS2113-AY1819S1-F09-4/main, pull requests merged in 2018-10, with the labels that each got.

#5 Panel shows all candidates and all their details.
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: status.ongoing, type.epic

#15 Updated userguide and edit command, parser
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCandidateCommand.java
  src/main/java/seedu/address/logic/parser/EditCandidateCommandParser.java
  src/main/java/seedu/address/logic/parser/RecruitBookParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCandidateCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCandidateDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCandidateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RecruitBookParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/systemtests/EditCandidateCommandSystemTest.java
Labels: type.bug

#26 Updated User Guide for Add-Job/Add-Company feature
  docs/UserGuide.adoc
Labels: priority.medium, type.task

#44 Integration/Unit tests for AddCompanyCommand/AddCompanyCommandParser
  src/test/java/seedu/recruit/logic/commands/AddCandidateCommandIntegrationTest.java
  src/test/java/seedu/recruit/logic/commands/AddCompanyCommandIntegrationTest.java
  src/test/java/seedu/recruit/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recruit/logic/parser/AddCandidateCommandParserTest.java
  src/test/java/seedu/recruit/logic/parser/AddCompanyCommandParserTest.java
  src/test/java/seedu/recruit/testutil/CompanyBuilder.java
  src/test/java/seedu/recruit/testutil/TypicalCompanies.java
Labels: priority.medium, type.task

#58 Fixed travis and fix status footer
  src/main/java/seedu/recruit/ui/MainWindow.java
  src/main/java/seedu/recruit/ui/StatusBarFooter.java
  src/main/resources/view/CompanyJobDetailsPanel.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/recruit/ui/CandidateCardTest.java
  src/test/java/seedu/recruit/ui/CandidateDetailsPanelTest.java
  src/test/java/seedu/recruit/ui/StatusBarFooterTest.java
  src/test/java/systemtests/CandidateBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.high, type.enhancement

#45 Added tests for Add-Company-Feature
  src/main/java/seedu/recruit/logic/commands/AddJobDetailsCommand.java
  src/main/java/seedu/recruit/model/company/CompanyName.java
  src/test/java/seedu/recruit/logic/commands/AddCandidateCommandIntegrationTest.java
  src/test/java/seedu/recruit/logic/commands/AddCandidateCommandTest.java
  src/test/java/seedu/recruit/logic/commands/AddCompanyCommandIntegrationTest.java
  src/test/java/seedu/recruit/logic/commands/AddCompanyCommandTest.java
  src/test/java/seedu/recruit/logic/commands/AddJobDetailsCommandTest.java
  src/test/java/seedu/recruit/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recruit/logic/parser/AddCandidateCommandParserTest.java
  src/test/java/seedu/recruit/logic/parser/AddCompanyCommandParserTest.java
  src/test/java/seedu/recruit/testutil/CompanyBuilder.java
  src/test/java/seedu/recruit/testutil/TypicalCompanies.java
Labels: priority.medium, type.task

#61 EditCompanyCommand and parser
  README.adoc
  src/main/java/seedu/recruit/logic/commands/EditCompanyCommand.java
  src/main/java/seedu/recruit/logic/parser/EditCompanyCommandParser.java
  src/main/java/seedu/recruit/logic/parser/RecruitBookParser.java
  src/test/java/seedu/recruit/logic/commands/EditCandidateCommandTest.java
Labels: priority.high, type.task

#68 Revised the sort command for different attributes and added editcompanycommand test
  src/main/java/seedu/recruit/commons/core/Messages.java
  src/main/java/seedu/recruit/logic/commands/EditCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/SortCommand.java
  src/main/java/seedu/recruit/logic/parser/RecruitBookParser.java
  src/main/java/seedu/recruit/logic/parser/SortCommandParser.java
  src/main/java/seedu/recruit/model/CandidateBook.java
  src/main/java/seedu/recruit/model/Model.java
  src/main/java/seedu/recruit/model/ModelManager.java
  src/main/java/seedu/recruit/model/candidate/UniqueCandidateList.java
  src/main/java/seedu/recruit/model/company/UniqueCompanyList.java
  src/test/java/seedu/recruit/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recruit/logic/commands/EditCandidateCommandTest.java
  src/test/java/seedu/recruit/logic/commands/EditCompanyCommandTest.java
  src/test/java/seedu/recruit/testutil/EditCompanyDescriptorBuilder.java
Labels: priority.medium, type.enhancement

#70 Add-job-feature
  src/main/java/seedu/recruit/model/CompanyBook.java
  src/main/java/seedu/recruit/model/joboffer/Job.java
  src/test/java/seedu/recruit/logic/commands/AddJobDetailsCommandIntegrationTest.java
  src/test/java/seedu/recruit/logic/commands/AddJobDetailsCommandTest.java
  src/test/java/seedu/recruit/testutil/JobOfferBuilder.java
Labels: priority.medium, type.task

#66 Merge Email Command to Master for v1.2
  docs/UserGuide.adoc
  src/main/java/seedu/recruit/commons/util/EmailUtil.java
  src/main/java/seedu/recruit/logic/CommandHistory.java
  src/main/java/seedu/recruit/logic/LogicManager.java
  src/main/java/seedu/recruit/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/Command.java
  src/main/java/seedu/recruit/logic/commands/EmailCommand.java
  src/main/java/seedu/recruit/logic/commands/emailcommand/EmailInitialiseCommand.java
  src/main/java/seedu/recruit/logic/commands/emailcommand/EmailSelectContentsCommand.java
  src/main/java/seedu/recruit/logic/commands/emailcommand/EmailSelectRecipientsCommand.java
  src/main/java/seedu/recruit/logic/commands/emailcommand/EmailSendCommand.java
  src/main/java/seedu/recruit/logic/parser/EmailParser.java
  src/main/java/seedu/recruit/logic/parser/RecruitBookParser.java
  src/main/java/seedu/recruit/model/Model.java
  src/main/java/seedu/recruit/model/ModelManager.java
  src/main/java/seedu/recruit/model/commons/Email.java
  src/main/java/seedu/recruit/model/company/Company.java
  src/test/java/seedu/recruit/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recruit/logic/parser/RecruitBookParserTest.java
Labels: priority.high, status.ongoing, type.story

#89 ListC and Listc Functions are available for use + Counts number of job offers per company & all job offers
  src/main/java/seedu/recruit/logic/commands/ListCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/ListCompanyCommand.java
  src/main/java/seedu/recruit/logic/parser/EmailParser.java
  src/main/java/seedu/recruit/logic/parser/RecruitBookParser.java
  src/main/java/seedu/recruit/ui/CompanyJobDetailsPanel.java
  src/main/java/seedu/recruit/ui/JobCard.java
  src/main/java/seedu/recruit/ui/MainWindow.java
  src/main/resources/view/CompanyJobDetailsPanel.fxml
  src/main/resources/view/JobCard.fxml
  src/test/java/seedu/recruit/logic/LogicManagerTest.java
  src/test/java/seedu/recruit/logic/commands/ListCandidateCommandTest.java
  src/test/java/seedu/recruit/logic/parser/RecruitBookParserTest.java
  src/test/java/seedu/recruit/ui/CommandBoxTest.java
  src/test/java/systemtests/CandidateBookSystemTest.java
Labels: priority.medium, type.enhancement

#91 checkstyle fixed, passed all tests
  src/test/java/seedu/recruit/logic/commands/ListCandidateCommandTest.java
Labels: type.bug

#93 Undo/Redo CompanyBook added, improved delete feature
  docs/UserGuide.adoc
  src/main/java/seedu/recruit/logic/commands/AddJobDetailsCommand.java
  src/main/java/seedu/recruit/logic/commands/DeleteCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/DeleteCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/DeleteJobOfferCommand.java
  src/main/java/seedu/recruit/logic/commands/RedoCandidateBookCommand.java
  src/main/java/seedu/recruit/logic/commands/RedoCompanyBookCommand.java
  src/main/java/seedu/recruit/logic/commands/UndoCandidateBookCommand.java
  src/main/java/seedu/recruit/logic/commands/UndoCompanyBookCommand.java
  src/main/java/seedu/recruit/logic/parser/ParserUtil.java
  src/main/java/seedu/recruit/logic/parser/RecruitBookParser.java
  src/test/java/seedu/recruit/logic/commands/DeleteCandidateCommandTest.java
  src/test/java/seedu/recruit/logic/commands/DeleteCompanyCommandTest.java
  src/test/java/seedu/recruit/logic/commands/EditCandidateCommandTest.java
  src/test/java/seedu/recruit/logic/commands/EditCompanyCommandTest.java
  src/test/java/seedu/recruit/logic/commands/RedoCandidateBookCommandTest.java
  src/test/java/seedu/recruit/logic/commands/UndoCandidateBookCommandTest.java
  src/test/java/seedu/recruit/logic/parser/RecruitBookParserTest.java
  src/test/java/systemtests/AddCandidateCommandSystemTest.java
  src/test/java/systemtests/ClearCandidateBookCommandSystemTest.java
  src/test/java/systemtests/DeleteCandidateCommandSystemTest.java
  src/test/java/systemtests/EditCandidateCommandSystemTest.java
  src/test/java/systemtests/FindCandidateCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.medium, type.enhancement

#94 [NEW] Shortlist command
  src/main/java/seedu/recruit/commons/events/ui/CompanyJobListDetailsPanelSelectionChangedEvent.java
  src/main/java/seedu/recruit/commons/events/ui/CompanyListDetailsPanelSelectionChangedEvent.java
  src/main/java/seedu/recruit/commons/events/ui/JumpToCompanyJobListRequestEvent.java
  src/main/java/seedu/recruit/commons/events/ui/JumpToCompanyListRequestEvent.java
  src/main/java/seedu/recruit/logic/commands/AddJobCommand.java
  src/main/java/seedu/recruit/logic/commands/AddJobDetailsCommand.java
  src/main/java/seedu/recruit/logic/commands/CancelCommand.java
  src/main/java/seedu/recruit/logic/commands/SelectCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/SelectCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/SelectJobCommand.java
  src/main/java/seedu/recruit/logic/commands/ShortlistCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/ShortlistCommand.java
  src/main/java/seedu/recruit/logic/commands/SwitchBookCommand.java
  src/main/java/seedu/recruit/logic/parser/RecruitBookParser.java
  src/main/java/seedu/recruit/logic/parser/SelectCandidateCommandParser.java
  src/main/java/seedu/recruit/logic/parser/SelectCommandParser.java
  src/main/java/seedu/recruit/logic/parser/SelectCompanyCommandParser.java
  src/main/java/seedu/recruit/logic/parser/SelectJobCommandParser.java
  src/main/java/seedu/recruit/logic/parser/ShortlistParser.java
  src/main/java/seedu/recruit/model/joboffer/JobOffer.java
  src/main/java/seedu/recruit/model/joboffer/UniqueJobList.java
  src/main/java/seedu/recruit/ui/CompanyJobDetailsPanel.java
  src/main/java/seedu/recruit/ui/MainWindow.java
  src/main/java/seedu/recruit/ui/ShortlistPanel.java
  src/main/resources/view/CandidateDetailsPanel.fxml
  src/main/resources/view/CompanyCard.fxml
  src/main/resources/view/CompanyJobDetailsPanel.fxml
  src/main/resources/view/JobCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ShortlistPanel.fxml
  src/test/java/seedu/recruit/logic/commands/SelectCandidateCommandTest.java
  src/test/java/seedu/recruit/logic/parser/RecruitBookParserTest.java
  src/test/java/seedu/recruit/logic/parser/SelectCandidateCommandParserTest.java
  src/test/java/seedu/recruit/ui/BrowserPanelTest.java
  src/test/java/systemtests/CandidateBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCandidateCommandSystemTest.java
Labels: priority.high, type.story

#105 Shortlists are now saved in CompanyBook
  src/main/java/seedu/recruit/logic/commands/AddCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/AddJobCommand.java
  src/main/java/seedu/recruit/logic/commands/AddJobDetailsCommand.java
  src/main/java/seedu/recruit/logic/commands/DeleteCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/DeleteCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/DeleteJobOfferCommand.java
  src/main/java/seedu/recruit/logic/commands/EditCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/EditJobDetailsCommand.java
  src/main/java/seedu/recruit/logic/commands/ShortlistCandidateCommand.java
  src/main/java/seedu/recruit/logic/parser/AddJobDetailsCommandParser.java
  src/main/java/seedu/recruit/model/CandidateBook.java
  src/main/java/seedu/recruit/model/CompanyBook.java
  src/main/java/seedu/recruit/model/Model.java
  src/main/java/seedu/recruit/model/ModelManager.java
  src/main/java/seedu/recruit/model/candidate/Candidate.java
  src/main/java/seedu/recruit/model/candidate/UniqueCandidateList.java
  src/main/java/seedu/recruit/model/candidate/exceptions/CandidateNotFoundException.java
  src/main/java/seedu/recruit/model/candidate/exceptions/DuplicateCandidateException.java
  src/main/java/seedu/recruit/model/company/UniqueCompanyList.java
  src/main/java/seedu/recruit/model/joboffer/JobOffer.java
  src/main/java/seedu/recruit/model/joboffer/UniqueJobList.java
  src/main/java/seedu/recruit/model/util/SampleDataUtil.java
  src/main/java/seedu/recruit/storage/XmlAdaptedCompany.java
  src/main/java/seedu/recruit/storage/XmlAdaptedJobOffer.java
  src/main/java/seedu/recruit/ui/CompanyJobDetailsPanel.java
  src/main/java/seedu/recruit/ui/MainWindow.java
  src/test/java/seedu/recruit/commons/util/XmlUtilTest.java
  src/test/java/seedu/recruit/logic/commands/AddCandidateCommandIntegrationTest.java
  src/test/java/seedu/recruit/logic/commands/AddCandidateCommandTest.java
  src/test/java/seedu/recruit/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recruit/logic/commands/EditCandidateCommandTest.java
  src/test/java/seedu/recruit/logic/parser/AddCandidateCommandParserTest.java
  src/test/java/seedu/recruit/logic/parser/RecruitBookParserTest.java
  src/test/java/seedu/recruit/model/CandidateBookTest.java
  src/test/java/seedu/recruit/model/candidate/CandidateTest.java
  src/test/java/seedu/recruit/model/candidate/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/recruit/model/candidate/UniqueCandidateListTest.java
  src/test/java/seedu/recruit/storage/XmlCandidateBookStorageTest.java
  src/test/java/seedu/recruit/testutil/CandidateBuilder.java
  src/test/java/seedu/recruit/testutil/JobOfferBuilder.java
  src/test/java/seedu/recruit/testutil/TypicalPersons.java
  src/test/java/seedu/recruit/ui/CandidateCardTest.java
  src/test/java/systemtests/AddCandidateCommandSystemTest.java
  src/test/java/systemtests/EditCandidateCommandSystemTest.java
Labels: priority.medium, type.task

#111 Added book change event
  src/main/java/seedu/recruit/logic/commands/EditCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/EditCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/EditJobDetailsCommand.java
  src/main/java/seedu/recruit/logic/commands/SortCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/SortCompanyCommand.java
  src/main/java/seedu/recruit/logic/parser/EditCandidateCommandParser.java
  src/main/java/seedu/recruit/model/CandidateBook.java
  src/main/java/seedu/recruit/model/Model.java
  src/main/java/seedu/recruit/model/candidate/UniqueCandidateList.java
Labels: priority.medium, type.bug

#118 Updated developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/johndoe.adoc
  docs/team/sxqnicholas.adoc
  src/main/java/seedu/recruit/logic/parser/FindCandidateCommandParser.java
  src/main/java/seedu/recruit/logic/parser/Prefix.java
  src/main/java/seedu/recruit/model/candidate/Candidate.java
  src/main/java/seedu/recruit/model/company/Company.java
  src/main/java/seedu/recruit/model/company/UniqueCompanyList.java
  src/test/java/seedu/recruit/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recruit/logic/commands/DeleteCandidateCommandTest.java
  src/test/java/seedu/recruit/logic/commands/FindCandidateCommandTest.java
  src/test/java/seedu/recruit/logic/parser/FindCandidateCommandParserTest.java
  src/test/java/seedu/recruit/logic/parser/RecruitBookParserTest.java
  src/test/java/seedu/recruit/model/candidate/CandidateContainsKeywordsPredicateTest.java
  src/test/java/seedu/recruit/testutil/CandidateContainsKeywordsPredicateBuilder.java
  src/test/java/systemtests/CandidateBookSystemTest.java
  src/test/java/systemtests/CompanyBookSystemTest.java
Labels: priority.medium, type.task

#121 Added blacklist command, parser and edited userguide for blacklist
  docs/UserGuide.adoc
  src/main/java/seedu/recruit/logic/commands/BlacklistCommand.java
  src/main/java/seedu/recruit/logic/commands/EditCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/EditCompanyCommand.java
  src/main/java/seedu/recruit/logic/commands/EditJobDetailsCommand.java
  src/main/java/seedu/recruit/logic/commands/SortCandidateCommand.java
  src/main/java/seedu/recruit/logic/commands/SortCompanyCommand.java
  src/main/java/seedu/recruit/logic/parser/BlacklistCommandParser.java
  src/main/java/seedu/recruit/logic/parser/CliSyntax.java
  src/main/java/seedu/recruit/logic/parser/DeleteCandidateCommandParser.java
  src/main/java/seedu/recruit/logic/parser/DeleteCompanyCommandParser.java
  src/main/java/seedu/recruit/logic/parser/DeleteJobOfferCommandParser.java
  src/main/java/seedu/recruit/logic/parser/RecruitBookParser.java
  src/main/java/seedu/recruit/ui/CandidateCard.java
Labels: priority.medium, type.story
